source("scripts/00_setup.R")
source("scripts/01_prepare_data.R")
source("scripts/01_validate_data.R")
source("scripts/02_descriptive_summary.R")
source("scripts/02_transformation_checks.R")
source("scripts/02_stationarity_checks.R")
source("scripts/02_exploratory_analysis.R")
source("scripts/03_model_comparison.R")
source("scripts/04_forecast_assessment.R")
source("scripts/04_selection_evidence.R")
source("scripts/05_output_manifest.R")
source("scripts/05_output_quality_checks.R")
source("scripts/05_report_input_summary.R")
source("scripts/05_session_info.R")
source("scripts/06_submission_readiness.R")

message("Workflow complete. Check outputs/figures and outputs/tables.")
